### ISSUE TITLE
Adding webid authentication

### ISSUE THREAD

**Issue by timbl** [linkeddata/node-ldp-httpd#16]
This (with rdfACL control) is one of the two most pressing things for this  project at the moment.

  @deiu notices that @magnetik had actually done a webid for node https://github.com/magnetik/node-webid so we forked it here in linkeddata and it remains to integrate it with the rest of the server.  Any volunteers?

**Comment by bergos** [comment]
@timbl @deiu Do you know [pubkey-login](https://github.com/bergos/pubkey-login)? It also contains some comment code which I used previously together with Apache httpd for resource based authentication, because node.js can't do renegotiation.

**Comment by martinmr** [comment]
At this moment, webid authentication already works. There are minor enhancements to be done, such as forwarding http requests to the https server. This problem is trivial when the two standard ports (80 and 443) are used but it's quite cumbersome when trying to use the same port, and I still haven't come up with a clean solution.
